const mongoose = require("mongoose");
const { Schema } = mongoose;

const cakeSchema = new Schema({
  recordType: { type: String, enum: ["cake", "order"], default: "cake" },
  cakeId: { type: String },
  userId: { type: String, required: true },
  bakerId: { type: String },
  bakerName: { type: String },
  customerId: { type: String },
  name: { type: String },
  description: { type: String },
  flavor: { type: String, required: true },
  shape: { type: String, required: true },
  size: { type: String, required: true },
  fillings: [{ type: String }], // legacy/compat with "filling" field in UI
  filling: { type: String },
  tiers: { type: String },
  frosting: { type: String },
  customMessage: { type: String },
  colorNotes: { type: String },
  dietaryNotes: { type: String },
  rushOrder: { type: Boolean, default: false },
  servings: { type: String },
  prepTime: { type: String },
  notes: { type: String },
  customerInstructions: { type: String },
  customerName: { type: String },
  customerEmail: { type: String },
  customerPhone: { type: String },
  customerLocation: { type: String },
  customerPhoto: { type: String },
  customerAvatarPreset: { type: String },
  deliveryMethod: { type: String },
  deliveryDate: { type: String },
  deliveryTime: { type: String },
  inspirationImage: { type: String },
  referenceImage: { type: String },
  mainImage: { type: String },
  galleryImages: [{ type: String }],
  allowCustomMessage: { type: Boolean, default: false },
  allowColorCustomization: { type: Boolean, default: false },
  availableForRushOrders: { type: Boolean, default: false },
  dietaryOptionsAvailable: { type: Boolean, default: false },
  toppings: [{ type: String }],
  status: { type: String, default: "pending" }, // pending, accepted, adjusted, declined
  adjustmentReason: { type: String },
  proposedPrice: { type: Number },
  previousPrice: { type: Number },
  statusBeforeAdjustment: { type: String },
  adjustmentRequestedAt: { type: Date },
  customerApprovalStatus: { type: String, default: "not_required" },
  reminderSentForDate: { type: String },
  cakeRating: { type: Number },
  bakerRating: { type: Number },
  reviewNote: { type: String },
  reviewCreatedAt: { type: Date },
  price: { type: Number, required: true },
  servings: String,
  prepTime: String,
  size: String,
  shape: String,
  flavor: String,
  filling: String,
  orders: { type: Number, default: 0 },
  rating: { type: Number, default: 5.0 },
  notes: String
});


const Cake = mongoose.model("Cake", cakeSchema, "cakes");

module.exports = Cake;
